### ISSUE TITLE
Figure out Facebook API for usage in Events section

### ISSUE THREAD

**Issue by ErinMHR** [PaulMHR/UWCookingClubWebsite#12]

**Comment by Fructokinase** [comment]
<!DOCTYPE html>
<html>

  <head>
    <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://d3js.org/d3.v4.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
  </head>

  <body>
    <div id="album-container">
      
      <div class="col-md-3 album-list">
        <p class="album-list-header">Albums</p>
        <div id="album-list-container">
        </div>
      </div>

      
      <div class="col-md-9 album-main">
      </div>
    </div>
  </body>


  <style>

  html, body{
    height: 100%;
    width: 100%;
    margin: 0;
  }

  #album-container{
    height: 100%;
  }

  .album-list-header{
    text-align: center;
    font-size: 50pt;
  }

  .album-list{
    height: 100%;
   background-color: lightgreen;
  }

  .album-main{
    height: 100%;
  }
  </style>

  <script type="text/javascript" charset="utf-8">
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '948538425257195',
      xfbml      : true,
      version    : 'v2.7'
    });

    this.album_lists = [];
    this.current_album = [];
    $(document).trigger('fbload');
  };

  var CC_USER_ID = '780926205363011';

  var get_albums = function(userid) {
     FB.api(
      "uwcookingclub/albums&access_token=948538425257195|OKEYNgz9w5m40brJViGZR7bAbsQ",
      function (response) {
        
      })
  }

  var bind_pictures = function(pictures) {
    for(p of pictures) {
      console.log(p.source);
    }
  }

  var pictures;

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

   $(document).on('fbload', function() {

    FB.api(
      "/" + CC_USER_ID + "/albums?access_token=948538425257195|OKEYNgz9w5m40brJViGZR7bAbsQ", function (response) {
      if (response && !response.error) {
        window.album_list = response.data;
        $(document).trigger('gotAlbumList');
      }
    })

   })

   $(document).on('gotAlbumList', function() {
    console.log("got album_list")
    var album_list_div = d3.select("#album-list-container");
    album_list_div.selectAll("button").data(window.album_list).enter().append("button")
    .attr("class", "btn btn-info btn-block album").attr("value", function(d){return d.id;})
    .append("p").text(function (d){ return d.name});
    $(document).trigger('appendedAlbumList');
   });

   $(document).on('appendedAlbumList', function(){
    $('button').click(function (){
      //gets the links for the photos based on the album id
      FB.api(
        "/" + this.value + "/photos?fields=source,picture,link,name&access_token=948538425257195|OKEYNgz9w5m40brJViGZR7bAbsQ",
        function (response) {
          if (response && !response.error) {
            window.current_album = response.data;
            $(document).trigger('albumChanged');
          } else {
            console.log("error", response.error);
          }
        }
      );
     })
   });

   $(document).on('albumChanged', function() {
    d3.select('.album-main').html('');
    d3.select('.album-main').selectAll('img').data(window.current_album).enter().append('img').attr('src', function (d) {
      ;return d.source;
    })
   })

   
  </script>

</html>

**Comment by Fructokinase** [comment]
I couldn't find a way to post html files were so I put my demo on AWS. 
here's the link 

http://fbapi-demo.s3-website-us-west-2.amazonaws.com/

Of course this won't be how things will look like in the end but it does show a few things

1)  that your idea of using FB API was amazing and it lets us gets a list of all albums and all respective photos
2) we don't need a backend for just photos
3) the logic flow will be something like calling the albums api to get a list of albums -> store that list of albums somewhere -> bind the view to the list of albums 

Now, things we need to think about before making the album view.
As you see in the demo, photos come in difference dimensions so to avoid dimension issues we should avoid changing the dimensions. 

We can limit 1 of the dimensions of the photo and write an algorhithm to determine the order of the photos (for example pinterest limits the horizontal width of the photo as there are always 5 photos in a row, however the height of the photo is different).

thoughts? ideas?

**Comment by Fructokinase** [comment]
oh yes! and implementation. This is important. We do need to somehow dynamically generate the HTML for the list of albums and such. In the demo it is done with d3, but there are other ways of doing it (Jquery, Angular and so on). It would be a good idea to talk about implementation for our learning as well.

**Comment by ErinMHR** [comment]
Thanks for posting that site! Pretty much exactly what I wanted. I'd prefer to order the photos chronologically myself. As for implementing the albums, would you mind putting up the source code of the demo site on a github repo and link it here? 

Personally, I'd love to get these albums into the form of fullPage.js slides, but I could just as easily work with other formats.

**Comment by Fructokinase** [comment]
<script> var a = 10; </script>

**Comment by ErinMHR** [comment]
Closed with Alex' most recent merge
