### ISSUE TITLE
Flesh out prototype design

### ISSUE THREAD

**Issue by ErinMHR** [PaulMHR/UWCookingClubWebsite#9]
### Summary

Before we create any more code, we should come together to create a design document of some kind to make sure that we know what belongs on each page, and what each page functions to do.
### Acceptance Criteria

This document should define each page on the website by providing:
- an outline of why a user would visit the page
- a list of what's included on the page
- a sketch of how the page should be composed

Currently, these pages include:
- the Home page, which provides the user with basic information about us and directs the user to other pages
- the About page, which gives more information as to what the Cooking Club does and why someone joins
- the Events page, which gives details of upcoming Cooking Club events
- the Contact Us page, which directs the user to how they can get in contact with us

**Comment by Fructokinase** [comment]
Javascript framework ideas

Fullpage scrolling -> fullpage.js
http://alvarotrigo.com/fullPage/

Viewport binding -> scrollreveal.js
https://scrollrevealjs.org/

**Comment by ErinMHR** [comment]
Closed with the following rough design document:

![img_4552](https://cloud.githubusercontent.com/assets/15352358/18490974/582805a0-79d2-11e6-8b4b-84cd3c8be58c.jpg)
